In [1]:
import mat73
import scipy
import numpy as np 
import matplotlib.pyplot as plt 



import scipy.io as sio 

In [2]:
from scipy.signal import butter, filtfilt

In [3]:
EEG = mat73.loadmat("s01.mat")

In [4]:
EEG.keys()

dict_keys(['RSVP', 'rest', 'senloc', 'test', 'train'])

In [7]:
EEG['RSVP'].keys()

dict_keys(['accuracy_t1', 'chanlocs', 'data', 'keyboard_response', 'markers_target', 'nbTrials', 'nbTrials_nontarget', 'nbTrials_target', 'srate', 'target'])

In [10]:
EEG['RSVP']['data']

array([[-22.28307343, -28.10352898, -31.72365379, ..., -58.98933029,
        -60.01023483, -61.5905838 ],
       [ 37.1714325 ,  29.36697006,  23.67318153, ..., -11.28929424,
        -11.91798306, -10.6981945 ],
       [  3.29181385,  -0.32949379,  -0.24470732, ..., -16.37091446,
        -15.91370106, -15.53999805],
       ...,
       [-16.4982357 , -21.23736   , -22.346735  , ..., -52.62401581,
        -52.4106636 , -50.44983673],
       [ 41.17608261,  36.11454391,  33.31502151, ..., -10.31910038,
        -11.26855564, -11.28609276],
       [ 16.31048203,  11.76788425,   9.03576183, ..., -21.76364326,
        -22.84052467, -23.53224564]])

In [12]:
EEG['RSVP']['data'].shape

(32, 166770)

In [19]:
type(EEG['test'])

list

In [27]:
EEG['test'][0]

{'chanlocs': [{'X': array(0.95047716),
   'Y': array(0.30882875),
   'Z': array(-0.0348995),
   'labels': 'FP1',
   'radius': array(0.51111111),
   'sph_phi': array(-2.),
   'sph_phi_besa': array(-72.),
   'sph_radius': array(1.),
   'sph_theta': array(18.),
   'sph_theta_besa': array(-92.),
   'theta': array(-18.)},
  {'X': array(0.88484606),
   'Y': array(0.37559487),
   'Z': array(0.27563736),
   'labels': 'AF3',
   'radius': array(0.41111111),
   'sph_phi': array(16.),
   'sph_phi_besa': array(-67.),
   'sph_radius': array(1.),
   'sph_theta': array(23.),
   'sph_theta_besa': array(-74.),
   'theta': array(-23.)},
  {'X': array(0.58742719),
   'Y': array(0.80852416),
   'Z': array(-0.0348995),
   'labels': 'F7',
   'radius': array(0.51111111),
   'sph_phi': array(-2.),
   'sph_phi_besa': array(-36.),
   'sph_radius': array(1.),
   'sph_theta': array(54.),
   'sph_theta_besa': array(-92.),
   'theta': array(-54.)},
  {'X': array(0.67302815),
   'Y': array(0.54500745),
   'Z': array(

In [42]:
print(len(EEG['train'][0]))
type(EEG['train'][0])

11


dict

In [26]:
EEG['train'][0].keys()

dict_keys(['chanlocs', 'data', 'markers_seq', 'markers_target', 'nbTrials', 'nbTrials_nontarget', 'nbTrials_target', 'online_acc', 'srate', 'text_result', 'text_to_spell'])

In [29]:
cal_01 = EEG['train'][0]

In [37]:

for cal in EEG['train']:              # 2 Calibration runs. 
    print("*************************")
    for key in cal:
        print(key, cal_01[key])


*************************
chanlocs [{'X': array(0.95047716), 'Y': array(0.30882875), 'Z': array(-0.0348995), 'labels': 'FP1', 'radius': array(0.51111111), 'sph_phi': array(-2.), 'sph_phi_besa': array(-72.), 'sph_radius': array(1.), 'sph_theta': array(18.), 'sph_theta_besa': array(-92.), 'theta': array(-18.)}, {'X': array(0.88484606), 'Y': array(0.37559487), 'Z': array(0.27563736), 'labels': 'AF3', 'radius': array(0.41111111), 'sph_phi': array(16.), 'sph_phi_besa': array(-67.), 'sph_radius': array(1.), 'sph_theta': array(23.), 'sph_theta_besa': array(-74.), 'theta': array(-23.)}, {'X': array(0.58742719), 'Y': array(0.80852416), 'Z': array(-0.0348995), 'labels': 'F7', 'radius': array(0.51111111), 'sph_phi': array(-2.), 'sph_phi_besa': array(-36.), 'sph_radius': array(1.), 'sph_theta': array(54.), 'sph_theta_besa': array(-92.), 'theta': array(-54.)}, {'X': array(0.67302815), 'Y': array(0.54500745), 'Z': array(0.5), 'labels': 'F3', 'radius': array(0.33333333), 'sph_phi': array(30.), 'sph_p

In [45]:
data = cal_01['data']
print(data.shape)             # 32 channels and the 1/512 * 117120 = nearly 4 minites 

(32, 117120)


In [46]:
data

array([[-15.93772623, -13.84439812, -12.74234446, ..., -23.03133021,
        -25.62126822, -27.68425291],
       [-15.65041468, -15.23191414, -15.78227289, ...,  -7.78646384,
         -7.46472353,  -8.12912195],
       [  2.57278064,   2.20179977,   0.73351495, ..., -24.29084121,
        -23.98951716, -25.21242445],
       ...,
       [ -6.61377117,  -4.233358  ,  -2.64722283, ...,  -7.58094512,
         -8.57125849,  -9.78834456],
       [ -8.66699431,  -7.81863174,  -7.47784193, ...,  11.34613599,
         10.72447687,  10.57287008],
       [ -3.10987565,  -3.27721128,  -3.21324463, ...,  -7.32540904,
         -6.70724101,  -6.90843027]])

In [60]:
print(cal_01['markers_target'])
markers = cal_01['markers_target']
print(type(markers))

print(0,np.count_nonzero(markers == 0))
print(1,np.count_nonzero(markers == 1)) # target IDs
print(2,np.count_nonzero(markers == 2)) # non-target IDs

[0. 0. 0. ... 0. 0. 0.]
<class 'numpy.ndarray'>
0 116220
1 150
2 750
